<?php

namespace Database\Seeders;

use App\Models\RoomUnitMapping;
use Illuminate\Database\Seeder;

/**
 * Seed room_unit_mappings — the hotel-unit → Beds24 mapping used by:
 *   - @j_booking_hotel_bot availability checks (ProcessBookingMessage)
 *   - Filament Availability page
 *   - Beds24 webhook room-name resolution
 *
 * Source of truth: regenerated 2026-04-20 from production
 * (jahongir-app.uz) after the bot-migration left the new VPS's table
 * empty. Covers BOTH properties (Jahongir Hotel + Jahongir Premium).
 *
 * Updating: if new rooms are added, extend the array below and re-run
 *   php artisan db:seed --class=RoomUnitMappingSeeder
 */
class RoomUnitMappingSeeder extends Seeder
{
    public function run(): void
    {
        $rooms = [
            // Jahongir Hotel (property 41097)
            [
                'unit_name' => '1',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '152726',
                'room_name' => '1 xona',
                'room_type' => '1 xona',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '2',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94986',
                'room_name' => 'Twin Room',
                'room_type' => 'Twin Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '3',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94991',
                'room_name' => 'Large Double Room',
                'room_type' => 'Large Double Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '4',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94984',
                'room_name' => 'Single Room',
                'room_type' => 'Single Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '5',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94991',
                'room_name' => 'Large Double Room',
                'room_type' => 'Large Double Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '6',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94986',
                'room_name' => 'Twin Room',
                'room_type' => 'Twin Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '7',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94986',
                'room_name' => 'Twin Room',
                'room_type' => 'Twin Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '8',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94984',
                'room_name' => 'Single Room',
                'room_type' => 'Single Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '9',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94984',
                'room_name' => 'Single Room',
                'room_type' => 'Single Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '10',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '144341',
                'room_name' => 'twin/double',
                'room_type' => 'twin/double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '11',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94982',
                'room_name' => 'Double Room',
                'room_type' => 'Double Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '12',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '144342',
                'room_name' => 'Junior Suite',
                'room_type' => 'Junior Suite',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '13',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '144341',
                'room_name' => 'twin/double',
                'room_type' => 'twin/double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '14',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '94982',
                'room_name' => 'Double Room',
                'room_type' => 'Double Room',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '15',
                'property_id' => '41097',
                'property_name' => 'Jahongir Hotel',
                'room_id' => '97215',
                'room_name' => 'Family Room',
                'room_type' => 'Family Room',
                'max_guests' => null,
                'base_price' => null,
            ],

            // Jahongir Premium (property 172793)
            [
                'unit_name' => '10',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377304',
                'room_name' => 'Deluxe triple',
                'room_type' => 'Deluxe triple',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '11',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377300',
                'room_name' => 'Standard Double',
                'room_type' => 'Standard Double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '12',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377291',
                'room_name' => 'Double or Twin',
                'room_type' => 'Double or Twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '14',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377299',
                'room_name' => 'Standard Queen',
                'room_type' => 'Standard Queen',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '15',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377301',
                'room_name' => 'Deluxe Double/twin',
                'room_type' => 'Deluxe Double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '16',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377302',
                'room_name' => 'Superior Double',
                'room_type' => 'Superior Double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '17',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377303',
                'room_name' => 'Superior double/twin',
                'room_type' => 'Superior double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '18',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377303',
                'room_name' => 'Superior double/twin',
                'room_type' => 'Superior double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '19',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377302',
                'room_name' => 'Superior Double',
                'room_type' => 'Superior Double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '20',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377304',
                'room_name' => 'Deluxe triple',
                'room_type' => 'Deluxe triple',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '21',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377300',
                'room_name' => 'Standard Double',
                'room_type' => 'Standard Double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '22',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377291',
                'room_name' => 'Double or Twin',
                'room_type' => 'Double or Twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '23',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377298',
                'room_name' => 'Deluxe Single',
                'room_type' => 'Deluxe Single',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '24',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377299',
                'room_name' => 'Standard Queen',
                'room_type' => 'Standard Queen',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '25',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377301',
                'room_name' => 'Deluxe Double/twin',
                'room_type' => 'Deluxe Double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '26',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377302',
                'room_name' => 'Superior Double',
                'room_type' => 'Superior Double',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '27',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377303',
                'room_name' => 'Superior double/twin',
                'room_type' => 'Superior double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '28',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377303',
                'room_name' => 'Superior double/twin',
                'room_type' => 'Superior double/twin',
                'max_guests' => null,
                'base_price' => null,
            ],
            [
                'unit_name' => '29',
                'property_id' => '172793',
                'property_name' => 'Jahongir Premium',
                'room_id' => '377302',
                'room_name' => 'Superior Double',
                'room_type' => 'Superior Double',
                'max_guests' => null,
                'base_price' => null,
            ],
        ];

        foreach ($rooms as $row) {
            RoomUnitMapping::updateOrCreate(
                [
                    'unit_name'   => $row['unit_name'],
                    'property_id' => $row['property_id'],
                ],
                $row,
            );
        }
    }
}
