[program:jahongir-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/jahongirnewapp/artisan queue:work database --sleep=3 --tries=5 --timeout=120 --queue=webhooks,telegram,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/jahongir-queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600
